### ISSUE TITLE
Error running Casual Impact

### ISSUE THREAD

**Issue by dariocorral** [WillianFuks/tfcausalimpact#16]
_

> File "C:\....\Anaconda3\envs\tf_py3.8\lib\site-packages\causalimpact\model.py", line 229, in build_bijector
>     bijector = SquareRootBijector()
> 
>   File "C:\...\Anaconda3\envs\tf_py3.8\lib\site-packages\causalimpact\model.py", line 467, in __init__
>     super().__init__(
> 
> TypeError: __init__() got an unexpected keyword argument 'parameters'

Thanks. This error comes from running the first example & data. Thanks in advance

**Comment by WillianFuks** [comment]
Hi @dariocorral ,

Not sure what's happening. Could you please send the results of your `pip freeze`?

As it seems looks like this is some package version incompatibility going on.

**Comment by dariocorral** [comment]
Hi @WillianFuks 

Yes, it was a package version incompatibility . I've created a new Conda environment and now it's working. Thanks a lot.
