### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by diogoalvesderesende** [WillianFuks/tfcausalimpact#29]
Hi!

I am getting the following error. The error also occurs in previous scripts that worked before.

AttributeError: module 'tensorflow_probability.python.sts' has no attribute 'regularize_series'

You can replicate it in the following link:
https://colab.research.google.com/drive/1YZtHDh01NIdU6DrCmGQT6abRF5Nzw5fL?usp=sharing

Let me know if there is something I can clarify.

Thanks, 
Diogo

**Comment by WillianFuks** [comment]
Hi @diogoalvesderesende ,

Thanks for opening this issue. As it seems you upgraded tensorflow probability which solves this issue but then another one arose ("index not available").

I'm investigating what happened, hope to get back to you soon.

**Comment by WillianFuks** [comment]
Hi @diogoalvesderesende ,

Sorry for the delay, I just released a new code to fix this bug. It was caused due changes in the TFP API and your data ended up falling in a scenario that was not tested.

Could you please confirm everything is working now? In the Colab you mentioned I installed the newest tfcausalimpact version `0.0.8rc1` and it seems to be fine now.

Let me know how it goes and I'll release it officially then.

Thanks,

Will

**Comment by diogoalvesderesende** [comment]
Hey!

Yeah, thanks a lot, now it works great. The one thing I get is 2
deprecation warnings. Are they intended, or do you know whether they make a
difference?

WARNING:tensorflow:From
/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/linalg/linear_operator_block_diag.py:238:
LinearOperator.graph_parents (from
tensorflow.python.ops.linalg.linear_operator) is deprecated and will
be removed in a future version.
Instructions for updating:
Do not call `graph_parents`.
WARNING:tensorflow:From
/usr/local/lib/python3.7/dist-packages/tensorflow_probability/python/distributions/distribution.py:346:
MultivariateNormalFullCovariance.__init__ (from
tensorflow_probability.python.distributions.mvn_full_covariance) is
deprecated and will be removed after 2019-12-01.
Instructions for updating:
`MultivariateNormalFullCovariance` is deprecated, use
`MultivariateNormalTriL(loc=loc,
scale_tril=tf.linalg.cholesky(covariance_matrix))` instead.



Thanks and best,
Diogo

**Comment by WillianFuks** [comment]
Good to know :). If you find any issues please let me know.

As for the warnings, they are internal to tensorflow probability, unfortunately we didn't find a way to turn them off yet (it's totally fine to ignore them though).

Best,

Will
