### ISSUE TITLE
Best way to turn .plot() into an image?

### ISSUE THREAD

**Issue by graingerkid** [WillianFuks/tfcausalimpact#40]
I'd like to use this lib as part of a Flask application but stuggling to pass it to the front end. Any suggestions?

**Comment by WillianFuks** [comment]
Hi @graingerkid ,

It's possible to use the option `ci.plot(show=False)` which keeps the matplotlib figure and axes still available. Then you can retrieve the image by running `plt.gcf()`. I've created this colab [notebook](https://colab.research.google.com/drive/1KzdvpUFi1XOFI_KZNShnhMA4YJQ5na4B?usp=sharing) showing how to do so.

Once you have access to the `figure` object then I suppose you can use the answer in this [SO](https://stackoverflow.com/a/50728936/1002277) thread to return the image as desired.

Hopefully this helps or gives you some ideas on how to proceed.

**Comment by graingerkid** [comment]
Ah - that works perfectly. Thanks for taking the time. Appreciate your help and your work
