### ISSUE TITLE
Example of custom model doesn't work

### ISSUE THREAD

**Issue by tarstars** [WillianFuks/tfcausalimpact#48]
Hello Will,

It's me again.

Now I was trying to run example with customized model:
  ```python
  import tensorflow_probability as tfp


  pre_y = data[:70, 0]
  pre_X = data[:70, 1:]
  obs_series = data.iloc[:, 0]
  local_linear = tfp.sts.LocalLinearTrend(observed_time_series=obs_series)
  seasonal = tfp.sts.Seasonal(nseasons=7, observed_time_series=obs_series)
  model = tfp.sts.Sum([local_linear, seasonal], observed_time_series=obs_series)

  ci = CausalImpact(data, pre_period, post_period, model=model)
  print(ci.summary())
  ```

There are a couple of comments for this code:
* pre_y, pre_X doesn't mention further, probably they should be pre_period, post_period
* my data has dtype np.float64 and hence model doesn't pass check for tf.float32 on model_validation step
* there is an error in nseasons=7 statement. Really it should be num_seasons.

Keeping all this in mind, I wrote my own lunapark:
```Python
data = generate_data()
obs_series = data.iloc[:, 0].astype("float32")
regular_data = tfp.sts.regularize_series(series=obs_series)
local_linear = tfp.sts.LocalLinearTrend(observed_time_series=regular_data)
seasonal = tfp.sts.Seasonal(num_seasons=12, observed_time_series=regular_data)
model = tfp.sts.Sum([local_linear, seasonal], observed_time_series=regular_data)

pre_period = ["2012-01-01", "2014-12-01"]
post_period = ["2015-01-01", "2016-11-01"]
ci = CausalImpact(regular_data, pre_period, post_period) # , model=model
print(ci.summary())
```

the whole runnable example you can find [there](https://pastebin.com/w0g6fEM1)

The problem is that this code runs with default model, but, for some unknown reason, produces nan values for the custom model. I'm looking forward to hear from your on this.

**Comment by WillianFuks** [comment]
Hi @tarstars ,

Thanks again for pointing that out. I just updated the docs as you can see [here](https://github.com/WillianFuks/tfcausalimpact/blob/improve_custom_model_docs/causalimpact/main.py#L180). Please let me know what you think.

As for your example, the `NaN` values are the result of not normalizing the data when building the model. So tfcausalimpact takes your input data that is not-normalized, normalizes it and then uses the model to compute the probability of observing the data, which results in zero.

This zero eventually is divided somewhere which results in the `NaN` results you observed.

To fix that is quite simple, you just need to normalize the data before using it:

 ```python
from causalimpact.misc import standardize


pre_period = ["2012-01-01", "2014-12-01"]
post_period = ["2015-01-01", "2016-11-01"]
data = tfp.sts.regularize_series(generate_data())
normed_data = standardize(data)[0].astype('float32')
obs_series = normed_data.loc[:pre_period[1], 0]

local_linear = tfp.sts.LocalLinearTrend(observed_time_series=obs_series)
seasonal = tfp.sts.Seasonal(num_seasons=12, observed_time_series=obs_series)
model = tfp.sts.Sum([local_linear, seasonal], observed_time_series=obs_series)


ci = CausalImpact(data, pre_period, post_period, model=model)
print(ci.summary())
```

Let me know if this works for you. As soon as everything is confirmed I'll merge the new code into master.

Best,

Will

**Comment by tarstars** [comment]
> Hi @tarstars ,
> 
> Thanks again for pointing that out. I just updated the docs as you can see [here](https://github.com/WillianFuks/tfcausalimpact/blob/improve_custom_model_docs/causalimpact/main.py#L180). Please let me know what you think.
> 
> As for your example, the `NaN` values are the result of not normalizing the data when building the model. So tfcausalimpact takes your input data that is not-normalized, normalizes it and then uses the model to compute the probability of observing the data, which results in zero.
> 
> This zero eventually is divided somewhere which results in the `NaN` results you observed.
> 
> To fix that is quite simple, you just need to normalize the data before using it:
> 
> ```python
> from causalimpact.misc import standardize
> 
> 
> pre_period = ["2012-01-01", "2014-12-01"]
> post_period = ["2015-01-01", "2016-11-01"]
> data = tfp.sts.regularize_series(generate_data())
> normed_data = standardize(data)[0].astype('float32')
> obs_series = normed_data.loc[:pre_period[1], 0]
> 
> local_linear = tfp.sts.LocalLinearTrend(observed_time_series=obs_series)
> seasonal = tfp.sts.Seasonal(num_seasons=12, observed_time_series=obs_series)
> model = tfp.sts.Sum([local_linear, seasonal], observed_time_series=obs_series)
> 
> 
> ci = CausalImpact(data, pre_period, post_period, model=model)
> print(ci.summary())
> ```
> 
> Let me know if this works for you. As soon as everything is confirmed I'll merge the new code into master.
> 
> Best,
> 
> Will

Will,

Thank you a lot for a prompt reaction. I just tested your patch and it works. Ship it!


Arseniy

**Comment by WillianFuks** [comment]
Thanks @tarstars for the reply. The new code has just been [released](https://pypi.org/project/tfcausalimpact/0.0.10/).

I'll close this thread now, if you find anything please let me know.

Best!

Will
