### ISSUE TITLE
Add compatibility for Python 3.10

### ISSUE THREAD

**Issue by der-eismann** [WillianFuks/tfcausalimpact#65]
Hey, thanks for this cool project! Unfortunately I am unable to use it on Fedora 36 since it ships with Python 3.10 and pip is denying the installation. Would be great if you could add compatibility for Python 3.10 (or even 3.11)!

**Comment by WillianFuks** [comment]
Definitely! I'll run some tests to see the compatibility with 3.10/3.11 and update it soon.

Tnx!

**Comment by WillianFuks** [comment]
Hi @der-eismann ,

Just released a newer rc version, could you please confirm if it's working?

    pip install tfcausalimpact==0.0.13rc0

Python 3.11 is still not supported by tensorflow so for now only 3.10 will be available.

Best,

**Comment by WillianFuks** [comment]
Hi @der-eismann ,

Just a quick check in, could you please confirm if the newer version works for you? In case it does I'll already release it.

Best,

Will
