### ISSUE TITLE
'CausalImpact' object has no attribute 'posterior_dist'

### ISSUE THREAD

**Issue by SaiAditya2595** [WillianFuks/tfcausalimpact#66]
Hi Willian, 
I am getting this error ''CausalImpact' object has no attribute 'posterior_dist' while running the notebook. Can you please tell me how to rectify this error?

Tensorflow version 2.9.2

**Comment by WillianFuks** [comment]
Hi @SaiAditya2595 ,

Unfortunately I couldn't reproduce your error. What version of tfcausalimpact are you using? And what python version?

Do you have a more specific section and line where you are getting this error?
