### ISSUE TITLE
Saving Figures of the Model Output

### ISSUE THREAD

**Issue by mekazanc** [WillianFuks/tfcausalimpact#70]
I want to save original figures but `model.plot()` returns None so that I could not save them with high quality. Adding such a feature definitely will be helpful.

**Comment by WillianFuks** [comment]
Hi @mekazanc ,

This package already offers [support](https://github.com/WillianFuks/tfcausalimpact/blob/master/causalimpact/plot.py#L41-L46) for that (maybe we should better document this feature still).

To manage your figures, you can run `ci.plot(show=False)` and then run commands such as:

```python
import matplotlib.pyplot as plt

plt.savefig(...)
```

This will save your plots as expected (you can also manipulate the axis as you wish as well).

Please let me know if this works for you,

**Comment by mekazanc** [comment]
Thank you very much @WillianFuks
