### ISSUE TITLE
how to specify which column is y

### ISSUE THREAD

**Issue by pamant22** [WillianFuks/tfcausalimpact#82]
As in the title, it's not clear to me unless I'm missing something how you specify which column in the dataframe is to be predicted. Is it the first column, as in the R package? Or is there some other way of doing this?

**Comment by WillianFuks** [comment]
Precisely. The first column is your observed response `y`. This package follows closely the R implementation, both share the same API.

**Comment by pamant22** [comment]
perfect, thanks
