### ISSUE TITLE
Question about output extraction

### ISSUE THREAD

**Issue by aazz7777** [WillianFuks/tfcausalimpact#88]
I'm wondering is there a way I can extract the prediction value separately  instead of plot.

**Comment by WillianFuks** [comment]
Hi @aazz7777 ,

Yes, this is possible. The inferences are stored in `ci.inferences` which is a pandas dataframe with all information extracted from the fitted model.

You also have access to `ci.summary_data` which relates to the summarization step, such as the cumulative information.

Let me know if this helps.

**Comment by aazz7777** [comment]
Thank you !
