### ISSUE TITLE
Spike-and-slab prior for regression coefficients

### ISSUE THREAD

**Issue by IvanUkhov** [WillianFuks/tfcausalimpact#9]
First off, thank you for the great package!

In the original paper, the authors use a spike-and-slab prior for the regression coefficients. Do I understand correctly that this is currently not the case in TFCausalImpact? If so, are there any plans in this regard? It might be a matter of replacing `LinearRegression` with `SparseLinearRegression`:

https://www.tensorflow.org/probability/api_docs/python/tfp/sts/SparseLinearRegression

**Comment by WillianFuks** [comment]
Hi @IvanUkhov ,

Thanks for this reference :)! I'll research more about it and if the `SparseLinearRegression` is closer to spike-and-slab I'll replace it soon.

When developing this package I compared several examples from the original R results with TFP using `LinearRegression` and even though they differed a bit they tended to converge to similar values. After reading about the sparse version it does seem to be more appropriate (maybe it better models some sort of Lasso regression which affects the log-prob after all).

Thanks,

Will

**Comment by WillianFuks** [comment]
Hi @IvanUkhov ,

Once again thanks for the information about the SparseLinearRegression, it does indeed model the weights in a very similar way as spike-and-slab from R does (this is in fact mentioned in the [docstring](https://github.com/tensorflow/probability/blob/v0.12.1/tensorflow_probability/python/sts/regression.py#L266-L391) of the class).

As a side note (for future reference also for those seeing this issue), the original R package does make some assumptions on its SpikeAndSlab implementation, mainly, they've considered that the `prior.df` (first component of the gamma distribution for the standard deviation of the slab component) is [50](https://github.com/google/CausalImpact/blob/master/R/impact_model.R#L225), the expected R^2 is [0.8](https://github.com/google/CausalImpact/blob/master/R/impact_model.R#L224) and model size is set as [3](https://github.com/google/CausalImpact/blob/master/R/impact_model.R#L222-L223). Internally, those values are [manipulated](https://github.com/google/CausalImpact/blob/master/R/impact_model.R#L222-L223) accordingly to set the prior estimation for the sparsity of data and its variance.

For TFP, it uses instead a horseshoe distribution and only parameter we can manipulate is the [weights_prior_scale](https://github.com/tensorflow/probability/blob/v0.12.1/tensorflow_probability/python/sts/regression.py#L395) which sets a prior for sparsity estimation as well (it's used when calculating the final values of the weights as a [multiplicative term](https://github.com/tensorflow/probability/blob/v0.12.1/tensorflow_probability/python/sts/regression.py#L491) for local and global scales.)

Currently this value has been set as default (0.1). If someone finds a value that better models the assumptions from the original R package please feel free to either let us know or send a PR.

Still, probably final results wouldn't change much so it's more of a side feature nice to have :).

Let me know @IvanUkhov if the newer version of this package solves this issue for you.

Best,

Will

**Comment by IvanUkhov** [comment]
Thank you! I think it will be beneficial for the package in general. One of the selling points of the paper is that they take care of the variable selection via a prior inducing sparsity, which was not present here in any form until now.
